#!/usr/bin/env node
import { promises as fs } from 'node:fs';
import path from 'node:path';
const ROOT = process.cwd();
const CONFIG = JSON.parse(await fs.readFile(path.join(ROOT, 'aidd.config.json'), 'utf8'));
const command = process.argv[2];
const args = process.argv.slice(3);
try {
  switch (command) {
    case 'check': await check(); break;
    case 'list': await listAll(); break;
    case 'module:create': await createModule(args); break;
    case 'module:list': await listModules(); break;
    case 'capability:create': await createCapability(args); break;
    case 'capability:list': await listCapabilities(); break;
    case 'slice': await createSlice(args); break;
    case 'slice:ready': await markSliceReady(args); break;
    case 'bundle': await bundleSlice(args); break;
    case 'capability': await capabilityPack(args); break;
    case 'clean': await clean(); break;
    default: help();
  }
} catch (error) { console.error(error.message); process.exit(1); }
function help(){ console.log('AIDD commands: check, list, module:create, capability:create, slice, slice:ready, bundle, capability, clean'); }
async function check(){ for (const file of ['common/index.md','modules/index.md','modules/_template/02-boundaries.md','capabilities/index.md','capabilities/_template/index.md','delivery/index.md','delivery/_template/delivery-slice.md','bundles/index.md']) await assertExists(file); console.log('AIDD check passed.'); }
async function assertExists(rel){ try{ await fs.access(path.join(ROOT, rel)); } catch { throw new Error(`Missing required file: ${rel}`); } }
async function createModule(args){ const slug=positional(args)[0]; if(!slug) throw new Error('Module slug is required.'); const title=flag(args,'title')??titleFromSlug(slug); const target=p(CONFIG.modulesDir,slug); if(await exists(target)) throw new Error(`Module already exists: ${slug}`); await copyDir(p(CONFIG.moduleTemplateDir),target); await replacePlaceholders(target, {'__MODULE_SLUG__':slug,'__MODULE_TITLE__':title}); await writeJson(path.join(target,'module.json'), {slug,title,status:'active',createdAt:new Date().toISOString(),deprecatedAt:null,archivedAt:null,reason:null,owns:[],dependsOn:[],exposes:[]}); await refreshModulesIndex(); console.log(`Created module: ${slug}`); }
async function createCapability(args){ const slug=positional(args)[0]; if(!slug) throw new Error('Capability slug is required.'); const title=flag(args,'title')??titleFromSlug(slug); const modules=parseCsv(flag(args,'modules')); const target=p(CONFIG.capabilitiesDir,slug); if(await exists(target)) throw new Error(`Capability already exists: ${slug}`); for(const moduleSlug of modules){ if(!(await exists(p(CONFIG.modulesDir,moduleSlug)))) throw new Error(`Referenced module does not exist: ${moduleSlug}`); } await copyDir(p(CONFIG.capabilityTemplateDir),target); await replacePlaceholders(target, {'__CAPABILITY_SLUG__':slug,'__CAPABILITY_TITLE__':title}); await writeJson(path.join(target,'capability.json'), {slug,title,status:'active',modules,createdAt:new Date().toISOString(),deprecatedAt:null,archivedAt:null,reason:null}); await refreshCapabilitiesIndex(); await refreshModulesIndex(); console.log(`Created capability: ${slug}`); }
async function createSlice(args){ const capabilitySlug=positional(args)[0]; if(!capabilitySlug) throw new Error('Capability slug is required.'); const id=flag(args,'id'); if(!id) throw new Error('--id is required.'); const title=flag(args,'title')??titleFromSlug(id); const capabilityDir=p(CONFIG.capabilitiesDir,capabilitySlug); if(!(await exists(capabilityDir))) throw new Error(`Capability not found: ${capabilitySlug}`); const capability=await readJson(path.join(capabilityDir,'capability.json')); const date=new Date().toISOString().slice(0,10); const sliceDir=p(CONFIG.deliveryDir,capabilitySlug,`${id}-${date}`); if(await exists(sliceDir)) throw new Error(`Slice already exists: ${path.relative(ROOT,sliceDir)}`); await fs.mkdir(sliceDir,{recursive:true}); const referencedModules=(capability.modules??[]).map(m=>`- ${titleFromSlug(m)} — \`modules/${m}/02-boundaries.md\``).join('\n') || 'No modules referenced.'; let slice=await fs.readFile(p(CONFIG.deliveryTemplateDir,'delivery-slice.md'),'utf8'); slice=slice.replaceAll('__SLICE_ID__',id).replaceAll('__SLICE_TITLE__',title).replaceAll('__CAPABILITY_SLUG__',capabilitySlug).replaceAll('__CAPABILITY_TITLE__',capability.title).replaceAll('__REFERENCED_MODULES__',referencedModules); await fs.writeFile(path.join(sliceDir,`${id}.md`),slice); await fs.writeFile(path.join(sliceDir,'index.md'),`# ${id}\n\n- [Delivery slice](./${id}.md)\n- [Manifest](./manifest.json)\n`); await writeJson(path.join(sliceDir,'manifest.json'), {id,title,capability:capabilitySlug,status:'draft',readyForImplementation:false,createdAt:new Date().toISOString(),modules:capability.modules??[]}); console.log(`Created draft slice: ${id}`); }
async function markSliceReady(args){ const id=positional(args)[0]; if(!id) throw new Error('Slice ID is required.'); const found=await findSlice(id); if(!found) throw new Error(`Slice not found: ${id}`); const content=await fs.readFile(path.join(found.dir,`${id}.md`),'utf8'); const missing=['## Delivery Scope','## Allowed Files','## Forbidden Files','## Tasks','## Acceptance Criteria','## AI Execution Contract','## Stop Conditions'].filter(s=>!content.includes(s)); if(missing.length) throw new Error(`Slice cannot be marked ready. Missing sections:\n${missing.map(x=>`- ${x}`).join('\n')}`); if(content.includes('TODO')) throw new Error('Slice cannot be marked ready while TODO markers remain.'); const manifestPath=path.join(found.dir,'manifest.json'); const manifest=await readJson(manifestPath); manifest.status='ready'; manifest.readyForImplementation=true; manifest.readyAt=new Date().toISOString(); await writeJson(manifestPath,manifest); console.log(`Marked slice ready: ${id}`); }
async function bundleSlice(args){ const id=positional(args)[0]; if(!id) throw new Error('Slice ID is required.'); const found=await findSlice(id); if(!found) throw new Error(`Slice not found: ${id}`); const manifest=await readJson(path.join(found.dir,'manifest.json')); if(manifest.status!=='ready'||!manifest.readyForImplementation) throw new Error(`Cannot bundle ${id}. Current status is ${manifest.status}. Run: npm run aidd:slice:ready -- ${id}`); const capability=await readJson(p(CONFIG.capabilitiesDir,manifest.capability,'capability.json')); const sliceContent=await fs.readFile(path.join(found.dir,`${id}.md`),'utf8'); const outDir=p(CONFIG.bundlesDir,id); await fs.mkdir(outDir,{recursive:true}); const moduleBoundaryLinks=(manifest.modules??[]).map(m=>`- modules/${m}/02-boundaries.md`).join('\n') || '- No module boundaries referenced.'; const plan=`# ${id} Implementation Plan\n\n## Work Sequence\n\n1. Read this bundle fully.\n2. Confirm the readiness gate.\n3. Review capability scope.\n4. Review referenced module boundaries.\n5. Complete tasks in order.\n6. Run the smallest relevant checks.\n7. Report files changed, tasks completed, checks run, and remaining risks.\n\n## Module Boundary Rules\n\n${moduleBoundaryLinks}\n`; const bundle=`# ${id} Implementation Bundle\n\n## Bundle Metadata\n\n- Slice ID: ${id}\n- Capability: ${capability.title}\n- Status at bundle creation: ${manifest.status}\n- Generated: ${new Date().toISOString()}\n\n## Context Loading Order\n\n1. This bundle.\n2. Capability: capabilities/${manifest.capability}/index.md\n3. Referenced module boundaries.\n4. Common delivery rules and standards.\n\n${plan}\n\n---\n\n${sliceContent}\n`; await fs.writeFile(path.join(outDir,`${id}.bundle.md`),bundle); await fs.writeFile(path.join(outDir,'implementation-plan.md'),plan); await writeJson(path.join(outDir,'manifest.json'), {id,capability:manifest.capability,modules:manifest.modules??[],generatedAt:new Date().toISOString(),source:path.relative(ROOT,found.dir)}); console.log(`Generated bundle: ${path.relative(ROOT,outDir)}`); }
async function capabilityPack(args){ const slug=positional(args)[0]; if(!slug) throw new Error('Capability slug is required.'); const dir=p(CONFIG.capabilitiesDir,slug); if(!(await exists(dir))) throw new Error(`Capability not found: ${slug}`); const manifest=await readJson(path.join(dir,'capability.json')); const outDir=p(CONFIG.bundlesDir,'capabilities'); await fs.mkdir(outDir,{recursive:true}); let content=`# ${manifest.title} Capability Pack\n\n## Referenced Modules\n\n${(manifest.modules??[]).map(m=>`- ${m}`).join('\n') || 'No modules referenced.'}\n\n`; for(const file of ['index.md',...CONFIG.capabilityFiles]){ const filePath=path.join(dir,file); if(await exists(filePath)) content+=`\n---\n\n${await fs.readFile(filePath,'utf8')}\n`; } await fs.writeFile(path.join(outDir,`${slug}.capability.md`),content); console.log(`Generated capability pack: ${path.join('bundles','capabilities',`${slug}.capability.md`)}`); }
async function listAll(){ await listModules(); await listCapabilities(); }
async function listModules(){ const modules=await readEntities(CONFIG.modulesDir,'module.json'); console.log('Modules:'); if(!modules.length) console.log('  none'); for(const m of modules) console.log(`  ${m.slug} — ${m.title} (${m.status})`); }
async function listCapabilities(){ const caps=await readEntities(CONFIG.capabilitiesDir,'capability.json'); console.log('Capabilities:'); if(!caps.length) console.log('  none'); for(const c of caps) console.log(`  ${c.slug} — ${c.title} (${c.status}; modules: ${(c.modules??[]).join(', ')||'none'})`); }
async function clean(){ const dir=p(CONFIG.bundlesDir); await fs.rm(dir,{recursive:true,force:true}); await fs.mkdir(dir,{recursive:true}); await fs.writeFile(path.join(dir,'index.md'),'# Bundles\n\nGenerated implementation bundles are written here.\n'); console.log('Cleaned generated bundles.'); }
async function refreshModulesIndex(){ const modules=await readEntities(CONFIG.modulesDir,'module.json'); const caps=await readEntities(CONFIG.capabilitiesDir,'capability.json'); const section=['## Active modules','',renderModuleList(modules.filter(x=>status(x)==='active'),caps,'No active modules yet.'),'','## Deprecated modules','',renderModuleList(modules.filter(x=>status(x)==='deprecated'),caps,'No deprecated modules.'),'','## Archived modules','',renderModuleList(modules.filter(x=>status(x)==='archived'),caps,'No archived modules.'),''].join('\n'); await replaceManagedSection(p(CONFIG.modulesDir,'index.md'),'## Active modules',section); }
async function refreshCapabilitiesIndex(){ const caps=await readEntities(CONFIG.capabilitiesDir,'capability.json'); const section=['## Active capabilities','',renderCapabilityList(caps.filter(x=>status(x)==='active'),'No active capabilities yet.'),'','## Deprecated capabilities','',renderCapabilityList(caps.filter(x=>status(x)==='deprecated'),'No deprecated capabilities.'),'','## Archived capabilities','',renderCapabilityList(caps.filter(x=>status(x)==='archived'),'No archived capabilities.'),''].join('\n'); await replaceManagedSection(p(CONFIG.capabilitiesDir,'index.md'),'## Active capabilities',section); }
function renderModuleList(modules,caps,empty){ if(!modules.length) return empty; return modules.map(m=>{ const related=caps.filter(c=>(c.modules??[]).includes(m.slug)); const relatedText=related.length ? ` — capabilities: ${related.map(c=>`[${c.title}](../capabilities/${c.slug}/index.md)`).join(', ')}` : ''; return `- [${m.title}](./${m.slug}/index.md)${relatedText}`; }).join('\n'); }
function renderCapabilityList(caps,empty){ if(!caps.length) return empty; return caps.map(c=>`- [${c.title}](./${c.slug}/index.md)${(c.modules??[]).length ? ` — modules: ${(c.modules??[]).join(', ')}` : ''}`).join('\n'); }
async function replaceManagedSection(filePath,heading,replacement){ const current=await fs.readFile(filePath,'utf8'); const next=current.includes(heading) ? current.replace(new RegExp(`${escapeRegExp(heading)}[\\s\\S]*$`,'m'),replacement) : `${current.trimEnd()}\n\n${replacement}`; await fs.writeFile(filePath,`${next.trimEnd()}\n`); }
async function readEntities(dirName,manifestName){ const dir=p(dirName); if(!(await exists(dir))) return []; const entries=await fs.readdir(dir,{withFileTypes:true}); const entities=[]; for(const entry of entries){ if(!entry.isDirectory()||entry.name.startsWith('_')) continue; const manifest=path.join(dir,entry.name,manifestName); if(await exists(manifest)) entities.push(await readJson(manifest)); } return entities.sort((a,b)=>a.title.localeCompare(b.title)); }
async function findSlice(id){ const deliveryDir=p(CONFIG.deliveryDir); if(!(await exists(deliveryDir))) return null; for(const cap of await fs.readdir(deliveryDir,{withFileTypes:true})){ if(!cap.isDirectory()||cap.name.startsWith('_')) continue; const parent=path.join(deliveryDir,cap.name); for(const slice of await fs.readdir(parent,{withFileTypes:true})){ if(slice.isDirectory()&&(slice.name.startsWith(`${id}-`)||slice.name===id)) return {capability:cap.name,dir:path.join(parent,slice.name)}; } } return null; }
async function copyDir(from,to){ await fs.mkdir(to,{recursive:true}); for(const entry of await fs.readdir(from,{withFileTypes:true})){ const source=path.join(from,entry.name), target=path.join(to,entry.name); if(entry.isDirectory()) await copyDir(source,target); else await fs.copyFile(source,target); } }
async function replacePlaceholders(root,replacements){ for(const entry of await fs.readdir(root,{withFileTypes:true})){ const full=path.join(root,entry.name); if(entry.isDirectory()){ await replacePlaceholders(full,replacements); continue; } if(!/\.(md|json)$/i.test(entry.name)) continue; let content=await fs.readFile(full,'utf8'); for(const [from,to] of Object.entries(replacements)) content=content.split(from).join(to); await fs.writeFile(full,content); } }
async function exists(filePath){ try{ await fs.access(filePath); return true; } catch { return false; } }
async function readJson(filePath){ return JSON.parse(await fs.readFile(filePath,'utf8')); }
async function writeJson(filePath,data){ await fs.writeFile(filePath,`${JSON.stringify(data,null,2)}\n`); }
function p(...parts){ return path.join(ROOT,...parts); }
function positional(args){ return args.filter(arg=>!arg.startsWith('--')); }
function flag(args,name){ const prefix=`--${name}=`; const inline=args.find(arg=>arg.startsWith(prefix)); if(inline) return inline.slice(prefix.length); const index=args.indexOf(`--${name}`); return index>=0 ? args[index+1] : null; }
function parseCsv(value){ return value ? value.split(',').map(x=>x.trim()).filter(Boolean) : []; }
function titleFromSlug(slug){ return slug.replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()); }
function status(entity){ return ['active','deprecated','archived'].includes(entity.status) ? entity.status : 'active'; }
function escapeRegExp(value){ return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'); }
